_select_data:
  aspect-ratios:
    - square
    - portrait
    - portrait-tall
    - landscape
    - landscape-wide

  column-sizes:
    col-12: Full Width
    col-6: One Half
    col-4: One Third
    col-3: One Quarter
    col-6_sm-12: One Half Desktop / Stacked on Mobile
    col-4_sm-12: One Third Desktop / Stacked on Mobile
    col-3_sm-12: One Quarter Desktop / Stacked on Mobile